run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80
  depguard:
    rules:
      Main:
        list-mode: strict
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/EvGesh4And/anti-bruteforce
          - github.com/BurntSushi/toml
          - github.com/caarlos0/env/v10
          - github.com/lmittmann/tint
          - golang.org/x/sync/errgroup
          - google.golang.org/grpc
          - google.golang.org/protobuf/types/known/emptypb
          - github.com/spf13/cobra
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/stretchr/testify/require
          - github.com/EvGesh4And/anti-bruteforce
          - google.golang.org/grpc
          - github.com/stretchr/testify/assert

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - dupl
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
