# ───── Go ─────
generate:          ## go generate ./...
	go generate ./...

lint: install-lint-deps
	go mod download
	golangci-lint run ./...

test:
	go test -race ./internal/...

.PHONY: generate lint test
