name: anti-bruteforce tests

on:
  push:
    branches:
      - main

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.24

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install protoc and Go plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

          # Устанавливаем плагины protoc для Go
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

          # Добавляем их в PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: make generate
        run: make generate
        working-directory: .

      - name: make lint
        run: make lint
        working-directory: .

      - name: make test
        run: make test
        working-directory: .